// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe30Q3zZ55wxxBLWAJ_AFdQ5vJPCQsM2Y',
    appId: '1:596387578775:web:10f54c0ff960f63badfad2',
    messagingSenderId: '596387578775',
    projectId: 'flutter-chat-a-6082a',
    authDomain: 'flutter-chat-a-6082a.firebaseapp.com',
    storageBucket: 'flutter-chat-a-6082a.appspot.com',
    measurementId: 'G-8G6107WLLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmlLEDjCgx_Y9gREzLFRRCXr3OFQtdr4',
    appId: '1:596387578775:android:0f2d7c2bbafa97c3adfad2',
    messagingSenderId: '596387578775',
    projectId: 'flutter-chat-a-6082a',
    storageBucket: 'flutter-chat-a-6082a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tXjCI3V3F9UWtQ0P1howXUaP5rlC1sk',
    appId: '1:596387578775:ios:a4f965091d543ea2adfad2',
    messagingSenderId: '596387578775',
    projectId: 'flutter-chat-a-6082a',
    storageBucket: 'flutter-chat-a-6082a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-tXjCI3V3F9UWtQ0P1howXUaP5rlC1sk',
    appId: '1:596387578775:ios:a4f965091d543ea2adfad2',
    messagingSenderId: '596387578775',
    projectId: 'flutter-chat-a-6082a',
    storageBucket: 'flutter-chat-a-6082a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe30Q3zZ55wxxBLWAJ_AFdQ5vJPCQsM2Y',
    appId: '1:596387578775:web:14139c0dcc157395adfad2',
    messagingSenderId: '596387578775',
    projectId: 'flutter-chat-a-6082a',
    authDomain: 'flutter-chat-a-6082a.firebaseapp.com',
    storageBucket: 'flutter-chat-a-6082a.appspot.com',
    measurementId: 'G-R0MZLJKNNW',
  );
}